Adding the option in backendConfig
Scille/parsec-cloud pull request #1581
Opened 2020-11-18 12:08 UTC by Sithi5

2020-11-18 13:22 UTC, touilleMan requested changes
I see the configuration... but where is the code to actually enforce https in the backend ? 😄

2020-11-18 13:22 UTC, touilleMan commented on tests/common.py
> +    "use_enforce_https",
`backend_enforce_https` to mimic `backend_over_ssl`&`backend_has_webhook` ?

2020-11-18 13:22 UTC, touilleMan commented on tests/backend/http/test_http.py
> +    print()
debug print to remove ?

2020-11-18 13:22 UTC, touilleMan commented on tests/backend/http/test_http.py
> +    assert backend.config.enforce_https is True
no need to check this given it is the responsibility of `customize_fixture` to enable this stuff (and if it is not enabled, the test should fail by itself)

2020-11-18 13:22 UTC, touilleMan commented on tests/backend/http/test_http.py
> +    status, headers, test = await backend_http_send(req=req)
I don't see what is tested here... how are we switching from http to https ?

2020-11-18 16:07 UTC, touilleMan commented
> My PR isn't done yet ^^

![image](https://user-images.githubusercontent.com/3187637/99555414-94181d00-29c0-11eb-824f-5ba30606d7d6.png)

2020-11-18 18:35 UTC, bitlogik commented
To help in the direction of strengthening your access server security, there also a couple of things you can do, on top of switching to HTTPS :
- Providing HSTS header flag, so that the client remember to use HTTPS (switch itself before sending a request)
- Use a 4096 bits RSA key for the server
- Similarly, use EC384 for EC group, not weak as sect163r1
- Use DNS Certification Authority Authorization (and DNSSEC)
- Use only the latest TLS "good" version (no more 1.0 nor 1.1)
- Use only a subset of encryption protocol, not recognized as "weak"
- and encryption protocol  which are "forward secrecy"
- Use OCSP stapling
- Fully disable session resumption only by cache

See the difference in ratings of the same service but with different proxy settings, these ratings are providing a view on the points to improve.

Analyzed by Qualys SSL Labs :
cloud.guardata.app : A+ score : https://www.ssllabs.com/ssltest/analyze.html?d=cloud.guardata.app
saas.parsec.cloud : B score : https://www.ssllabs.com/ssltest/analyze.html?d=saas.parsec.cloud&s=52.214.73.151

Analyzed by imirhil :
cloud.guardata.app : A+ score : https://tls.imirhil.fr/https/cloud.guardata.app
saas.parsec.cloud : B score : https://tls.imirhil.fr/https/saas.parsec.cloud

Maybe an opened issue dedicated to this matter would be relevant ? Let us know.

2020-11-30 13:01 UTC, touilleMan commented
@bitlogik thanks for the feedback

As you say, SSL support is a slippery slope and you end up very fast with a lot of options that should be taken into account (so in the end more code for less tested but security-sensitive features).
I think the line is clear on this topic: production deployment should serve Parsec behind a reverse proxy so all those advanced concerned shouldn't be a concern to us. The main reason Parsec server has SSL support is to allow simple deployment for test purpose and for the unittests.

Regarding this PR, I think `X-Forward-Proto` support on application side is pretty common and simple enough.

2020-11-30 13:01 UTC, touilleMan approved these changes

2020-11-30 13:03 UTC, merged