Fix cli share_workspace
Scille/parsec-cloud pull request #1686
Opened 2021-04-12 08:55 UTC by AntoineDupre

closes  #1682

2021-04-23 09:21 UTC, touilleMan requested changes

2021-04-23 09:21 UTC, touilleMan commented on parsec/core/cli/share_workspace.py
> +    "user_role", default="READER", type=click.Choice(("READER", "CONTRIBUTOR", "MANAGER", "OWNER"))
Aaaaaand while I'm at it: how do we know what to provide for user_id ?
Given user_id is now mainly an uuid, it's hard for the end user to know about it (there is no cli command to retreive this uuid from the human handle for instance)

The solutions I see:
1) provide a `--recipiant` option that search on the human handle
2) create a new `parsec core human_find` command to retrieve a user_id from human handle
3) do both (so you can choose between `share_workspace [...] --recipiant=john@doe.com` or `share_workspace [...] --user-id=415e9218e43845d388694b734141a288`, typically if you're working on a non-human user)

If we choose to do changes on this, I think we should do that in another PR ;-)

2021-04-23 09:21 UTC, touilleMan commented on parsec/core/cli/share_workspace.py
> +    "user_role", default="READER", type=click.Choice(("READER", "CONTRIBUTOR", "MANAGER", "OWNER"))
Big realization: There is now way to pass the `None` value !!!!! so we cannot remove a role...

2021-04-23 09:21 UTC, touilleMan commented on parsec/core/cli/share_workspace.py
> +    roles = {
As a matter of fact (after realizing we also need the `None`, see below), I think we should do all the conversion in the click argument:
```python

class WorkspaceRoleChoice(click.Choice):
    STR_TO_ROLE = {
        "NONE": None,
        *{role.value: role for role in WorkspaceRole}
    }

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def convert(self, value, param, ctx):
        ret = super().convert(value, param, ctx)
        return self.STR_TO_ROLE[ret.upper()]

@click.argument(
    "--role", type=WorkspaceRoleChoice(case_sensitive=False)
)
[...]
```

2021-05-03 08:11 UTC, AntoineDupre commented on parsec/core/cli/share_workspace.py
> +    "user_role", default="READER", type=click.Choice(("READER", "CONTRIBUTOR", "MANAGER", "OWNER"))
I created a new issue about retriving the human handle from cli ##1712


The lack of `None` value in click is a bit problematic. I setup a conversion method: 
```python

    @staticmethod
    def fix_none_choice(choice):
        return None if choice == "None" else choice
```

2021-05-03 08:32 UTC, AntoineDupre commented on parsec/core/cli/share_workspace.py
> +        await core.user_fs.workspace_share(f"/{name}", user_id, role)
Oh yes ! it has to be converted. I put a helper in the `LoggedCore` to find the WorkspaceEntry from a name:
```python
    def find_workspace_from_name(self, workspace_name: str):
        for workspace in self.user_fs.get_user_manifest().workspaces:
            if workspace_name == workspace.name:
                return workspace
        raise FSWorkspaceNotFoundError(f"Unknown workspace {workspace_name}")
```

2021-05-03 08:33 UTC, AntoineDupre commented on parsec/core/cli/share_workspace.py
> +    roles = {
:+1:

2021-05-03 21:56 UTC, touilleMan commented on parsec/core/cli/share_workspace.py
> +        await core.user_fs.workspace_share(f"/{name}", user_id, role)
I think we'd better use the workspace-id directly (especially given we can have multiple workspaces with the same name !)

But this is "fine enough" for now, we should merge this PR as is and open an issue (especially given we will probably need a way to list the user's workspaces and it ids with this change !)

2021-05-10 08:07 UTC, touilleMan approved these changes

2021-05-10 08:08 UTC, merged