Improve macfuse installation
Scille/parsec-cloud pull request #1777
Opened 2021-07-05 10:03 UTC by Ironicbay

New window looks like this:
<img width="864" alt="Capture d’écran 2021-07-05 à 11 47 12" src="https://user-images.githubusercontent.com/41511029/124454521-e27bff80-dd88-11eb-8c47-fe05bdba9a3f.png">

The `<a href>` link should redirect to a detailed guide with pictures, steps etc.

2021-07-05 10:10 UTC, Max-7 approved these changes

2021-07-05 10:18 UTC, Max-7 requested changes

2021-07-05 10:18 UTC, Max-7 commented on parsec/core/gui/tr/parsec_en.po
> +"<a href=\"https://www.google.com/search?q=todo\">here</a>."
Fix the URL.

2021-07-05 10:18 UTC, Max-7 commented on parsec/core/gui/tr/parsec_fr.po
> +"<a href=\"https://www.google.com/search?q=%C3%A0+faire\">ici</a>."
Fix the URL.

2021-07-05 10:18 UTC, Max-7 commented on parsec/core/gui/custom_dialogs.py
> +    def __init__(self, message, dialog=None, button_text=None, url=None):
Make the URL mandatory.

2021-07-06 07:54 UTC, Ironicbay commented
Current widget look: 
<img width="861" alt="Capture d’écran 2021-07-06 à 09 53 56" src="https://user-images.githubusercontent.com/41511029/124563274-2ed64680-de40-11eb-90f6-cc2ae92b34cb.png">

2021-07-06 13:33 UTC, touilleMan approved these changes
👍

2021-07-06 13:36 UTC, merged