Implement trio deadlock detection in mountpoint.fs_access
Scille/parsec-cloud pull request #1851
Opened 2021-09-13 10:39 UTC by vxgmichel

2021-09-13 13:04 UTC, touilleMan requested changes

2021-09-13 13:04 UTC, touilleMan commented on parsec/core/mountpoint/thread_fs_access.py
> +            coro = trio._util.coroutine_or_error(afn, *args)
why not `return await afn(*args)` ?

2021-09-14 12:03 UTC, vxgmichel commented on parsec/core/mountpoint/thread_fs_access.py
> +    def callback():
```python
In [23]: %%time
    ...: for i in range(50000):
    ...:     fd = os.open("/home/vinmic/Parsec/alice_workspace/test", os.O_CREAT)
    ...:     os.close(fd)
    ...: 
CPU times: user 1.4 s, sys: 1.42 s, total: 2.83 s
Wall time: 46.9 s

In [24]: %%time
    ...: for i in range(50000):
    ...:     fd = os.open("/home/vinmic/Parsec/alice_workspace/test", os.O_CREAT)
    ...:     os.close(fd)
    ...: 
CPU times: user 1.08 s, sys: 1.48 s, total: 2.56 s
Wall time: 47.9 s
```
It's a ~2% slowdown on very fast operations such as `open` and `close`.

2021-09-20 17:26 UTC, touilleMan approved these changes
lgtm

2021-09-20 17:26 UTC, merged