Type DEFAULT_BLOCK_SIZE
Scille/parsec-cloud pull request #2459
Opened 2022-06-13 13:13 UTC by TimeEngineer

2022-06-13 13:56 UTC, FirelightFlagboy approved these changes

2022-06-13 14:14 UTC, touilleMan requested changes

2022-06-13 20:06 UTC, TimeEngineer commented on oxidation/crates/parsec_api_types/src/manifest.rs
> +    pub const unsafe fn new_unchecked(n: u64) -> Self {
There is no equivalent, there is no Blocksize type in Python, we introduced this type in schema for number >= 8
See: https://doc.rust-lang.org/stable/std/num/struct.NonZeroU32.html#method.new_unchecked

2022-06-14 13:17 UTC, touilleMan approved these changes

2022-06-14 13:27 UTC, merged