Fix/2514 invalid from http redirection
Scille/parsec-cloud pull request #2520
Opened 2022-06-27 13:16 UTC by FirelightFlagboy

depends on #2516 

closes #2514

2022-06-27 13:33 UTC, touilleMan requested changes

2022-06-27 13:33 UTC, touilleMan commented on oxidation/crates/parsec_api_types/src/addr.rs
> +                if path_segments.next() != Some("redirect") {
Good catch !

2022-06-28 06:55 UTC, FirelightFlagboy commented on oxidation/crates/parsec_api_types/tests/test_addr/test_from_http_redirect.rs
> +use rstest::rstest;
done

2022-06-28 06:55 UTC, FirelightFlagboy commented on oxidation/crates/parsec_api_types/tests/test_addr/test_from_http_redirect.rs
> +use rstest::rstest;
but i prefer smaller files

2022-06-28 06:55 UTC, FirelightFlagboy commented on oxidation/crates/parsec_api_types/tests/test_addr/test_from_http_redirect.rs
> +#[case("https://foo.bar/redirect", true)]
done

2022-06-28 09:03 UTC, touilleMan approved these changes
👍

2022-06-28 09:10 UTC, merged