Bump macos version in CI
Scille/parsec-cloud pull request #2842
Opened 2022-08-17 08:36 UTC by Ironicbay

Closes #2837

2022-08-17 08:56 UTC, touilleMan commented
please note you also have to update the macos version in test-rust-matrix (which seems to currently uses macos-12)

2022-08-26 12:43 UTC, FirelightFlagboy requested changes

2022-08-26 12:43 UTC, FirelightFlagboy commented on .github/workflows/ci.yml
> +  SYSTEM_VERSION_COMPAT: 0 # Variable set for python to work in macos 12 as expected
Not needed for the CI

2022-08-26 12:43 UTC, FirelightFlagboy commented on .github/workflows/package-ci.yml
> +        os: [ macos-11, macos-12 ]
```suggestion
    runs-on: macos-${{ matrix.macos-version }}
    name: '🍎 macOS ${{ matrix.macos-version }}: 📦 Packaging (test app)'
    needs: package-macos-build-app
    strategy:
      fail-fast: false
      matrix:
        macos-version: [ 11, 12 ]
```

2022-09-05 08:00 UTC, FirelightFlagboy approved these changes

2022-09-05 08:26 UTC, FirelightFlagboy approved these changes

2022-09-07 07:27 UTC, merged