fix vuejs testing tools
Scille/parsec-cloud pull request #2977
Opened 2022-08-30 08:08 UTC by Landeers

fix #2872

2022-08-30 09:42 UTC, FirelightFlagboy requested changes

2022-08-30 09:42 UTC, FirelightFlagboy commented on .github/workflows/ci.yml
>          run: npm run build
Now that we have tests for the webapp, move this step in a proper job in `package-ci.yml`.
I can help you with that

2022-08-30 09:42 UTC, FirelightFlagboy commented on .github/dependabot.yml
> +    open-pull-requests-limit: 2
Don't we also lack `binding/neon` & `binding/web` ?

- `binding/neon` have a `package-lock.json`
- `binding/web` have a `yarn.lock` but empty

2023-01-05 22:02 UTC, touilleMan commented on .github/workflows/package-ci.yml
> +    name: ⚡ Package Vuejs
```suggestion
    name: ⚡ Package web app
```

2023-01-05 22:03 UTC, touilleMan approved these changes

2023-01-06 07:49 UTC, FirelightFlagboy approved these changes

2023-01-06 10:16 UTC, merged