2.13
Scille/parsec-cloud pull request #3180
Opened 2022-10-01 18:45 UTC by touilleMan

2022-10-04 13:19 UTC, FirelightFlagboy requested changes

2022-10-04 13:19 UTC, FirelightFlagboy commented on HISTORY.rst
> +  3rd party through HTTP A webhook services is a sequester service with an
```suggestion
  3rd party through HTTP A webhook services as a sequester service with an
```

2022-10-04 13:19 UTC, FirelightFlagboy commented on HISTORY.rst
> +* Fix an error that desync postgresql timestamptz type  (`#3071
```suggestion
* Fix an error that desync postgresql timestampt type  (`#3071
```

2022-10-10 09:18 UTC, FirelightFlagboy commented on HISTORY.rst
> +  3rd party through HTTP A webhook services is a sequester service with an
done

2022-10-10 09:47 UTC, FirelightFlagboy commented on HISTORY.rst
> +* Fix an error that desync postgresql timestamptz type  (`#3071
done

2022-10-11 07:10 UTC, FirelightFlagboy reviewed
Some fragment are waiting to be merge into the changelog for the next RC

2022-10-13 14:37 UTC, FirelightFlagboy approved these changes

2022-10-14 06:41 UTC, FirelightFlagboy reviewed
A fragment is still present

2022-10-19 14:44 UTC, FirelightFlagboy approved these changes

2022-10-19 16:13 UTC, vxgmichel commented
Follow up on #3340

2022-10-19 16:13 UTC, closed without merging