Binding invitation email sent status
Scille/parsec-cloud pull request #3223
Opened 2022-10-07 09:42 UTC by Volham22

This close #3220

2022-10-07 11:54 UTC, FirelightFlagboy requested changes
Are you sure about the filename of the news fragment ?

2022-10-07 11:54 UTC, FirelightFlagboy commented on parsec/api/protocol/invite.py
> +            raise ValidationError(f"Invalid type `{value}`")
Can we move this method into `pyo3` ?

2022-10-07 11:54 UTC, FirelightFlagboy commented on parsec/api/protocol/invite.py
> +            raise ValidationError(f"Invalid type `{value}`")
ditto

2022-10-10 07:56 UTC, TimeEngineer approved these changes

2022-10-10 08:09 UTC, FirelightFlagboy approved these changes

2022-10-10 08:19 UTC, FirelightFlagboy approved these changes

2022-10-10 08:23 UTC, FirelightFlagboy approved these changes

2022-10-10 08:52 UTC, FirelightFlagboy approved these changes

2022-10-10 09:54 UTC, merged