Binding invitation deleted reason
Scille/parsec-cloud pull request #3237
Opened 2022-10-10 13:20 UTC by Volham22

This fix #3232

2022-10-11 08:05 UTC, touilleMan requested changes

2022-10-11 10:01 UTC, Volham22 commented
I've also replaced all python enum usage by the new one

2022-10-13 09:02 UTC, FirelightFlagboy approved these changes

2022-10-13 09:16 UTC, FirelightFlagboy approved these changes

2022-10-20 12:04 UTC, FirelightFlagboy approved these changes

2022-11-14 17:22 UTC, closed without merging