Remove noop --timestamp param from `parsec core run` CLI command
Scille/parsec-cloud pull request #3346
Opened 2022-10-19 23:09 UTC by touilleMan

2022-10-20 07:37 UTC, FirelightFlagboy reviewed
I don't see how the issue #3345 is related to this PR

The issue point a problem with the option `--mountpoint`
but here we remove the option `--timestamp`

Maybe change the title of the issue if it was miss labeled, to prevent confusion in the changelog :thinking:

2022-10-24 18:03 UTC, touilleMan commented
> The issue point a problem with the option --mountpoint
> but here we remove the option --timestamp

The issue was precisely the `--timestamp` did nothing, so there is two way to fix this 1) implement it 2) remove it
We don't have need for this feature for the moment, so the fix is 2)

2022-10-25 06:24 UTC, FirelightFlagboy commented
> The issue was precisely the `--timestamp`

Again, it's not the cause

The issue's title is

> `parsec core run` has a useless **`--mountpount`** parameter

2022-10-25 08:32 UTC, touilleMan commented
Ha ! I finally understand: I wrote `--mountpoint` by mistake in the original issue ! I've corrected it ;-)

2022-10-25 08:37 UTC, FirelightFlagboy approved these changes
Just a minor suggestion for the fragment, but it's ok

2022-10-25 08:37 UTC, FirelightFlagboy commented on newsfragments/3345.misc.rst
> +Remove noop --timestamp param from `parsec core run` CLI command
```suggestion
Remove noop `--timestamp` param from `parsec core run` CLI command
```

2022-10-25 10:04 UTC, FirelightFlagboy requested changes

2022-10-25 10:04 UTC, FirelightFlagboy commented on newsfragments/3345.misc.rst
> +Remove noop `--timestamp`` param from `parsec core run` CLI command
```suggestion
Remove noop `--timestamp` param from `parsec core run` CLI command
```

2022-10-25 14:34 UTC, merged