mypy: Added mypy typing for`greet_device_widget` and `greet_user_widget`
Scille/parsec-cloud pull request #3393
Opened 2022-10-26 13:17 UTC by Volham22

This close #3392

2022-10-26 14:53 UTC, TimeEngineer approved these changes

2022-11-03 07:22 UTC, Max-7 requested changes

2022-11-03 07:22 UTC, Max-7 commented on parsec/core/gui/greet_device_widget.py
> +    async def get_claimer_sas(self) -> Tuple[object, object]:
Should be `Tuple[SASCode, list[SASCode]]`

2022-11-03 07:22 UTC, Max-7 commented on parsec/core/gui/greet_device_widget.py
> +    def __init__(self, core: LoggedCore, jobs_ctx: Any, invite_addr: BackendInvitationAddr) -> None:
`jobs_ctx` is a `QtToTrioJobScheduler`

2022-11-03 07:22 UTC, Max-7 commented on parsec/core/gui/greet_device_widget.py
> +    def show_modal(cls, core: LoggedCore, jobs_ctx: Any, invite_addr: BackendInvitationAddr, parent: QWidget, on_finished: Callable[..., None]) -> GreetDeviceWidget:  # type: ignore[misc]
`jobs_ctx` is a `QtToTrioJobScheduler`

2022-11-03 07:22 UTC, Max-7 commented on parsec/core/gui/greet_user_widget.py
> +    async def get_claimer_sas(self) -> Tuple[object, object]:
`Tuple[SASCode, list[SASCode]]`

2022-11-03 07:22 UTC, Max-7 commented on parsec/core/gui/greet_user_widget.py
> +    def __init__(self, jobs_ctx: Any, greeter: Any) -> None:
`QtToTrioJobScheduler` and `Greeter`

2022-11-03 07:22 UTC, Max-7 commented on parsec/core/gui/greet_user_widget.py
> +        self, jobs_ctx: Any, greeter: Any, user_profile_outsider_allowed: bool = False
`QtToTrioJobScheduler` and `Greeter`

2022-11-03 07:22 UTC, Max-7 commented on parsec/core/gui/greet_user_widget.py
> +    def __init__(self, jobs_ctx: Any, greeter: Any) -> None:
`QtToTrioJobScheduler` and `Greeter`

2022-11-03 07:22 UTC, Max-7 commented on parsec/core/gui/greet_user_widget.py
> +    def __init__(self, core: LoggedCore, jobs_ctx: Any, token: InvitationToken) -> None:
`QtToTrioJobScheduler`

2022-11-03 07:22 UTC, Max-7 commented on parsec/core/gui/greet_user_widget.py
> +    def show_modal(cls, core: LoggedCore, jobs_ctx: Any, token: InvitationToken, parent: QWidget, on_finished: Callable[..., None]) -> GreetUserWidget:  # type: ignore[misc]
`QtToTrioJobScheduler`

2022-11-03 09:22 UTC, Max-7 commented on parsec/core/gui/greet_device_widget.py
> +        self, jobs_ctx: Any, greeter: Any, invite_addr: BackendInvitationAddr, core: LoggedCore
`QtToTrioJobScheduler` and `Greeter` (may have missed it the first time, sorry)

2022-11-03 09:23 UTC, Max-7 requested changes

2022-11-03 09:23 UTC, Max-7 commented on parsec/core/gui/greet_device_widget.py
> +    def __init__(self, jobs_ctx: Any, greeter: Any) -> None:
`QtToTrioJobScheduler` and `Greeter`

2022-11-03 11:11 UTC, Max-7 approved these changes

2022-11-03 16:15 UTC, vxgmichel approved these changes

2022-11-04 08:42 UTC, merged