Oxidation api crypto
Scille/parsec-cloud pull request #3430
Opened 2022-10-28 13:33 UTC by TimeEngineer

# What have changed ?

Migrate all the crypto API

- [ ] Does this PR affect the User ?

closes #3429
depends on #3427

2022-11-09 15:16 UTC, FirelightFlagboy requested changes

2022-11-09 15:16 UTC, FirelightFlagboy commented on oxidation/libparsec/crates/crypto/src/rustcrypto/secret.rs
> +//§ https://github.com/sodiumoxide/sodiumoxide/blob/master/libsodium-sys/src/sodium_bindings.rs#L127
```suggestion
/// https://github.com/sodiumoxide/sodiumoxide/blob/master/libsodium-sys/src/sodium_bindings.rs#L127
```

2022-11-09 15:16 UTC, FirelightFlagboy commented on oxidation/libparsec/crates/crypto/src/rustcrypto/secret.rs
> +// https://github.com/sodiumoxide/sodiumoxide/blob/master/libsodium-sys/src/sodium_bindings.rs#L128
```suggestion
/// https://github.com/sodiumoxide/sodiumoxide/blob/master/libsodium-sys/src/sodium_bindings.rs#L128
```

2022-11-09 15:16 UTC, FirelightFlagboy commented on oxidation/libparsec/crates/crypto/src/rustcrypto/secret.rs
> +const MEMLIMIT_INTERACTIVE: u32 = 33554432;
```suggestion
const MEMLIMIT_INTERACTIVE: u32 = 33_554_432;
```
Use `_` to make the number more readable

2022-11-09 15:16 UTC, FirelightFlagboy commented on parsec/_parsec_pyi/crypto.pyi
> +    def generate_recovery_passphrase(cls) -> Tuple[str, SecretKey]: ...
```suggestion
    def generate_recovery_passphrase(cls) -> tuple[str, SecretKey]: ...
```

We don't have to import `Tuple`

2022-11-09 15:34 UTC, FirelightFlagboy approved these changes

2022-11-11 19:44 UTC, Max-7 approved these changes

2022-11-14 09:03 UTC, merged