Type `core.gui.new_version`
Scille/parsec-cloud pull request #3435
Opened 2022-10-28 15:08 UTC by FirelightFlagboy

2022-10-28 15:20 UTC, TimeEngineer requested changes

2022-10-28 15:20 UTC, TimeEngineer commented on parsec/core/gui/new_version.py
> +    def add_version_field(self, data: dict[str, Any]) -> dict[str, Any]:  # type: ignore[misc]
Use object instead

2022-10-31 10:07 UTC, FirelightFlagboy commented on parsec/core/gui/new_version.py
> +    def add_version_field(self, data: dict[str, Any]) -> dict[str, Any]:  # type: ignore[misc]
done

2022-11-02 15:54 UTC, TimeEngineer approved these changes

2022-11-03 06:45 UTC, Max-7 commented on parsec/core/gui/new_version.py
> +        # Cannot retrieve the releases (typically due to no internet access)
How can you tell @touilleMan wrote the code? There's a `retreive` somewhere.

2022-11-03 06:45 UTC, Max-7 approved these changes

2022-11-03 07:14 UTC, merged