Mypy gui settings
Scille/parsec-cloud pull request #3450
Opened 2022-10-31 15:47 UTC by TimeEngineer

# What have changed ?

- [ ] Does this PR affect the User ?

closes #3449

2022-10-31 16:29 UTC, Volham22 approved these changes

2022-10-31 16:29 UTC, Volham22 commented on parsec/core/gui/settings_dialog.py
> +from parsec.core.gui.ui.settings_dialog import Ui_SettingsDialog  # type: ignore[import]
Maybe we can add an exception for that in `mypy.ini`?

2022-11-02 11:23 UTC, Volham22 approved these changes

2022-11-02 12:10 UTC, Max-7 requested changes

2022-11-02 12:10 UTC, Max-7 commented on parsec/core/gui/settings_dialog.py
>  # Parsec Cloud (https://parsec.cloud) Copyright (c) AGPL-3.0 2016-present Scille SAS
I think this whole file can be deleted, it's never imported and `settings_dialog.ui` doesn't exist either.

2022-11-02 15:30 UTC, Max-7 approved these changes

2022-11-02 17:38 UTC, merged