mypy: Added mypy typing for `core.utils`
Scille/parsec-cloud pull request #3517
Opened 2022-11-07 15:09 UTC by Volham22

# What has changed ?

This closes #3513 

- [ ] Does this PR affect the User ?

2022-11-08 07:50 UTC, FirelightFlagboy approved these changes

2022-11-09 09:01 UTC, TimeEngineer requested changes

2022-11-09 09:01 UTC, TimeEngineer commented on parsec/utils.py
> +        import trio_asyncio  # type: ignore[import]
Add in mypy.ini instead

2022-11-09 10:00 UTC, FirelightFlagboy commented on parsec/stubs/trio_asyncio/__init__.pyi
> +) -> _T: ...
```suggestion
_R = TypeVar("_R")

def run(
    proc: Callable[..., Awaitable[_R]], *args: object, queue_len: Optional[int] = None
) -> _R: ...
```

I prefer `R` in this case (`R` as in `Return`)

2022-11-09 10:21 UTC, FirelightFlagboy approved these changes

2022-11-09 12:48 UTC, FirelightFlagboy approved these changes

2022-11-09 14:01 UTC, TimeEngineer approved these changes

2022-11-10 17:16 UTC, TimeEngineer approved these changes

2022-11-14 06:52 UTC, Max-7 approved these changes

2022-11-14 08:24 UTC, merged