Oxidation remove UUID
Scille/parsec-cloud pull request #3587
Opened 2022-11-15 17:03 UTC by TimeEngineer

# What has changed ?

Add `UUID` auto conversion for postgres

- [ ] Does this PR affect the User ?

2022-11-15 17:19 UTC, Volham22 requested changes

2022-11-17 08:18 UTC, Volham22 approved these changes

2022-11-18 08:16 UTC, FirelightFlagboy commented on parsec/backend/swift_blockstore.py
> +    return f"{organization_id.str}/{id}"
Given that comment, we may want to be more explicit and provide a `as_hyphenated` method

2022-11-18 12:12 UTC, Volham22 approved these changes

2022-11-18 13:22 UTC, FirelightFlagboy approved these changes

2022-11-18 16:00 UTC, FirelightFlagboy requested changes

2022-11-18 16:00 UTC, FirelightFlagboy commented on parsec/core/pki/accepter.py
> +        enrollment_id = cast(UUID, enrollment["enrollment_id"])
Should use `EnrollmentID`

2022-11-18 16:17 UTC, TimeEngineer commented on parsec/backend/postgresql/pki.py
> +                    enrollment_id=UUID(entry["enrollment_id"]),
Done here: https://github.com/Scille/parsec-cloud/pull/3585

2022-11-18 16:17 UTC, TimeEngineer commented on parsec/backend/postgresql/pki.py
> +                                enrollment_id=UUID(row["enrollment_id"]),
Done here: https://github.com/Scille/parsec-cloud/pull/3585

2022-11-22 08:53 UTC, FirelightFlagboy approved these changes

2022-11-22 12:29 UTC, Max-7 approved these changes

2022-11-22 12:35 UTC, merged