Fix client API version reporting in the server logs
Scille/parsec-cloud pull request #3831
Opened 2023-01-02 17:23 UTC by vxgmichel

Fix issue #3830

2023-01-02 17:49 UTC, touilleMan requested changes

2023-01-02 17:49 UTC, touilleMan commented on tests/backend/test_ws_handshake.py
> +        assert f"(client/server API version: {API_VERSION}/{API_VERSION})" in caplog.text
It would be better to have 2 different version for client and server

2023-01-02 17:49 UTC, touilleMan commented on tests/backend/test_ws_handshake.py
> +        assert f"(client/server API version: {API_VERSION}/{API_VERSION})" in caplog.text
`test_rpc_handshake.py` should also be modified

2023-01-02 19:30 UTC, touilleMan approved these changes
lgtm

2023-01-03 07:51 UTC, FirelightFlagboy approved these changes

2023-01-03 10:59 UTC, merged