Bump rust
Scille/parsec-cloud pull request #3891
Opened 2023-01-11 12:28 UTC by TimeEngineer

# What has changed ?

- [ ] Does this PR affect the User ?

2023-01-11 12:39 UTC, touilleMan requested changes

2023-01-11 12:39 UTC, touilleMan commented on .github/workflows/ci.yml
> -  rust-version: 1.65.0
This line can be entirely removed given the action `actions-rust-lang/setup-rust-toolchain` directly uses `rust-toolchain.toml`

2023-01-11 12:56 UTC, FirelightFlagboy approved these changes

2023-01-11 15:26 UTC, FirelightFlagboy approved these changes

2023-01-12 08:47 UTC, touilleMan approved these changes

2023-01-12 10:57 UTC, merged