Fix available device key file path type
Scille/parsec-cloud pull request #3943
Opened 2023-01-23 10:17 UTC by Volham22

# What has changed ?

This closes #3942 . When we return a `PathBuf` with `pyo3` the default conversion gives a python string. We want this conversion to yield a `pathlib.Path` because it makes path manipulation easier in python.

- [ ] Does this PR affect the User ?

2023-01-23 10:55 UTC, FirelightFlagboy requested changes

2023-01-23 10:55 UTC, FirelightFlagboy commented on src/binding_utils.rs
> +            .unwrap()
Use `expect`

2023-01-23 14:47 UTC, Volham22 commented on src/binding_utils.rs
> +            .unwrap()
Done.

2023-01-23 17:21 UTC, FirelightFlagboy requested changes

2023-01-23 17:21 UTC, FirelightFlagboy commented on src/binding_utils.rs
> +            .unwrap()
Missing this unwrap

2023-01-23 19:19 UTC, TimeEngineer commented on src/binding_utils.rs
> +    types::{PyBytes, PyTuple},
group import

2023-01-24 08:57 UTC, Volham22 commented on src/binding_utils.rs
> +            .call1(PyTuple::new(py, [self.0.to_str().unwrap()]))
Yes it works.

2023-01-24 09:06 UTC, FirelightFlagboy approved these changes

2023-01-24 10:09 UTC, merged