Oxidation device file
Scille/parsec-cloud pull request #3948
Opened 2023-01-23 13:56 UTC by TimeEngineer

# What has changed ?

- [ ] Does this PR affect the User ?

2023-01-23 15:03 UTC, Volham22 requested changes

2023-01-23 15:28 UTC, TimeEngineer commented on src/data/local_device_file.rs
> +use pyo3::{
True

2023-01-23 19:25 UTC, TimeEngineer commented on tests/common/smartcard.py
> +            ) -> Tuple[DeviceFileType, bytes, bytes | None, bytes | None, str | None, bytes | None]:
Done

2023-01-23 19:25 UTC, TimeEngineer commented on src/data/mod.rs
>  mod certif;
Done

2023-01-23 19:25 UTC, TimeEngineer commented on src/data/local_device_file.rs
> +use pyo3::{
Done

2023-01-24 08:58 UTC, Volham22 approved these changes

2023-01-24 14:11 UTC, FirelightFlagboy approved these changes

2023-01-25 10:18 UTC, FirelightFlagboy approved these changes

2023-01-25 13:07 UTC, merged