Add RFC 1003 Update user profile
Scille/parsec-cloud pull request #4096
Opened 2023-02-27 11:01 UTC by touilleMan

# What has changed ?

- [ ] Does this PR affect the User ?

2023-02-27 11:04 UTC, FirelightFlagboy requested changes
Holding to give time to merge the previous rfcs and have the correct id :p

2023-02-28 08:00 UTC, FirelightFlagboy requested changes

2023-02-28 09:26 UTC, touilleMan commented on docs/rfcs/0038-update-user-profile.md
> +Current remote loader system use a 1h cache system. This works ok enough considering
no this is another cache system ;-)

2023-02-28 09:28 UTC, touilleMan commented on docs/rfcs/0038-update-user-profile.md
> +occurs to send a query to the server in order to make sure we aren't short of a certificate.
The server takes a bit of time to propagate the new certificates to the clients, so in the meantime a client can try to read a data that appear to him as invalid

2023-02-28 10:07 UTC, touilleMan commented on docs/rfcs/0038-update-user-profile.md
> +1) Server receive an authenticated query for a `user_create` command
the other items are in the present tense, so no need for past here ;-)

2023-02-28 10:10 UTC, FirelightFlagboy commented on docs/rfcs/0038-update-user-profile.md
> +occurs to send a query to the server in order to make sure we aren't short of a certificate.
ok

2023-03-13 10:19 UTC, FirelightFlagboy approved these changes

2023-03-15 13:25 UTC, merged