Add RFCS
Scille/parsec-cloud pull request #4099
Opened 2023-02-27 15:35 UTC by FirelightFlagboy

2023-02-27 15:38 UTC, FirelightFlagboy commented
Current the RFCs are extract from some issue.
If you see that an important issue wasn't convert => write a comment ;).
If you see that a converted RFC should not be added => open a discussion :shrug:.

2023-02-27 15:40 UTC, TimeEngineer requested changes

2023-02-27 15:40 UTC, TimeEngineer commented on docs/rfcs/0036-rust-to-js-number-conversion-in-the-bindings.md
> +Currently we only support `i32` type as lower common denominator for number.
This is wrong, we also support `u32`

2023-02-27 15:46 UTC, FirelightFlagboy commented on docs/rfcs/0036-rust-to-js-number-conversion-in-the-bindings.md
> +Currently we only support `i32` type as lower common denominator for number.
Does this please you ?

```suggestion
Currently we only support `i32` & `u32` types as lower common denominator for number.
```

2023-02-27 15:48 UTC, TimeEngineer commented on docs/rfcs/0036-rust-to-js-number-conversion-in-the-bindings.md
> +Currently we only support `i32` type as lower common denominator for number.
Yes

2023-02-27 15:52 UTC, mmmarcos reviewed
C'est pas mal ! même si à ce stade je ne suis pas capable de reviewer le contenu des RFC existants ^^

2023-02-27 15:52 UTC, mmmarcos commented on docs/rfcs/0000-how-to-write-rfcs.md
> +This document indicate the `do` & `don't` when writing a RFC file.
```suggestion
This document indicate the `do` & `don't` when writing an RFC file.
```

2023-02-27 15:52 UTC, mmmarcos commented on docs/rfcs/0000-how-to-write-rfcs.md
> +I recommend using those vscode extensions:
```suggestion
I recommend using these vscode extensions:
```

2023-02-27 15:59 UTC, TimeEngineer approved these changes

2023-02-28 10:14 UTC, touilleMan commented on docs/rfcs/0037-shamir-based-recovery.md
> +            4  // TODO: we most likely want to do an API bump for this feature !
Those are rookie number, we need to pump them up !

2023-02-28 10:15 UTC, touilleMan commented on docs/rfcs/0037-shamir-based-recovery.md
> +                        "name": "brief",
Yes, the server will store this certificate

2023-02-28 10:18 UTC, touilleMan commented on docs/rfcs/0037-shamir-based-recovery.md
> +- the number of shares must be greater or equal to the threshold (and threshold must be >= 1)
I don't understand this change: we are listing the thing that are enforced by the server, user only allowed to have a single share would be something to write, but user able to have multiple shares is the default (and it's already mentioned earlier)

2023-02-28 10:22 UTC, touilleMan commented on docs/rfcs/0037-shamir-based-recovery.md
> +                        "type": "Vec<Bytes>"
This was related to **future evolution 3**, I removed the comment then

2023-02-28 10:30 UTC, FirelightFlagboy commented on docs/rfcs/0037-shamir-based-recovery.md
> +                        "name": "brief",
:+1:

2023-02-28 10:31 UTC, FirelightFlagboy commented on docs/rfcs/0037-shamir-based-recovery.md
> +- the number of shares must be greater or equal to the threshold (and threshold must be >= 1)
It's just a suggestion, I find it more clear with it

2023-03-03 13:49 UTC, mmmarcos approved these changes
:+1:

2023-03-03 15:39 UTC, merged