Add CORS to testbed server
Scille/parsec-cloud pull request #4151
Opened 2023-03-03 10:00 UTC by Max-7

# What has changed ?

- [ ] Does this PR affect the User ?

2023-03-03 10:20 UTC, TimeEngineer approved these changes

2023-03-03 11:03 UTC, FirelightFlagboy approved these changes

2023-03-03 13:17 UTC, touilleMan approved these changes

2023-03-08 12:07 UTC, FirelightFlagboy requested changes
Can you remove the commit `merge master into ...` ?

2023-03-09 07:43 UTC, FirelightFlagboy approved these changes

2023-03-10 13:40 UTC, merged