Switch to Vite for building GUI
Scille/parsec-cloud pull request #4229
Opened 2023-03-14 20:06 UTC by touilleMan

# What has changed ?

- [ ] Does this PR affect the User ?

depend on #4228

2023-03-15 07:57 UTC, FirelightFlagboy reviewed
This PR is really big, can it be splited ?

2023-03-15 08:36 UTC, FirelightFlagboy requested changes

2023-03-15 08:36 UTC, FirelightFlagboy commented on oxidation/client-vite/.gitignore
Some of those values should be in the main gitignore

2023-03-15 08:41 UTC, FirelightFlagboy commented on oxidation/client-vite/capacitor.config.ts
Why this file is the same as `oxidation/client-vite/electron/capacitor.config.ts` ?

2023-03-15 08:41 UTC, FirelightFlagboy commented on oxidation/client-vite/electron/electron-builder.config.json
> +        "category": "your.app.category.type",
Do we really want the category to be `your.app.category.type` ?

2023-03-17 10:08 UTC, FirelightFlagboy reviewed
Could it be possible to rename `client-vite` to `client` and the current `client` folder to `client-old` ?

2023-04-14 14:58 UTC, FirelightFlagboy approved these changes

2023-04-14 15:22 UTC, FirelightFlagboy approved these changes

2023-04-14 15:25 UTC, NicoTuxx approved these changes

2023-04-14 18:36 UTC, merged