Oxidation parsec test macro
Scille/parsec-cloud pull request #4338
Opened 2023-03-29 17:12 UTC by TimeEngineer

# What has changed ?

- [ ] Does this PR affect the User ?

closes #4267

2023-03-30 07:07 UTC, FirelightFlagboy requested changes
I don't think we should use the crate `libparsec_parsec_test` where we don't use the testbed.

2023-03-30 08:49 UTC, touilleMan commented
![image](https://user-images.githubusercontent.com/3187637/228782160-32b22476-9508-4282-b413-ccc70167087b.png)

2023-03-30 08:58 UTC, TimeEngineer commented
Why ? It's independant

2023-03-30 09:22 UTC, touilleMan requested changes

2023-03-30 09:23 UTC, TimeEngineer commented on oxidation/libparsec/crates/client_connection/tests/auth_cmds.rs
> +    let client = reqwest::ClientBuilder::new()
Nothing more

2023-03-30 09:30 UTC, TimeEngineer commented
> > Why ? It's independant
> 
> > **Smaller is better**. You should include the minimal set of changes required
> > to address the subject of the pull request.

The PR address to use `parsec_test` instead of all `test`, you can have 2 PRs for that but changing 1 line is not the big part of this PR

2023-03-30 10:31 UTC, TimeEngineer commented on oxidation/libparsec/crates/client_connection/Cargo.toml
> +libparsec_parsec_test = { path = "../parsec_test" }
Done

2023-03-30 11:04 UTC, TimeEngineer commented on oxidation/libparsec/crates/parsec_test/Cargo.toml
> +syn = { version = "1.0.109" }
Current Branch (all):
```
real    1m54,068s
user    18m11,588s
sys     1m13,581s
```

Master (all):
```
real    1m23,605s
user    17m25,681s
sys     1m11,931s
```

Current Branch (core_fs):
```
real    0m7,708s
user    0m14,242s
sys     0m1,494s
```

Master (core_fs):
```
real    0m7,696s
user    0m14,201s
sys     0m1,568s
```

2023-03-30 12:51 UTC, FirelightFlagboy reviewed
With that PR the amount of cyclic dependencies is increase on the test level, can you confirm that rust-analyzer is working properly ?

2023-03-30 12:51 UTC, FirelightFlagboy commented on oxidation/libparsec/crates/tests_macros/src/lib.rs
Can you add `with_log` ?

2023-03-30 15:42 UTC, FirelightFlagboy commented on oxidation/libparsec/crates/tests_macros/src/lib.rs
Currently, we can't enable the log in the test, we lack the use of `test_log`.

I propose to add `with_log` that way we only enable for test that need it.

2023-03-30 20:13 UTC, TimeEngineer commented on oxidation/libparsec/crates/tests_macros/src/lib.rs
`test_log` macro is removed because my macro initialize the `logger`

2023-03-30 20:14 UTC, TimeEngineer commented
> With that PR the amount of cyclic dependencies is increase on the test level, can you confirm that rust-analyzer is working properly ?

It won't work because `tests_fixtures` broke it with testbed :stuck_out_tongue:

2023-04-03 12:56 UTC, FirelightFlagboy approved these changes

2023-04-03 14:40 UTC, FirelightFlagboy approved these changes

2023-04-03 16:56 UTC, merged