Ms reorganize components
Scille/parsec-cloud pull request #4970
Opened 2023-08-08 13:12 UTC by NicoTuxx

## Describe your changes

## Checklist

Before you submit this pull request, please make sure to:

- [ ] Keep changes in the pull request as small as possible
   
- [ ] Ensure the commit history is sanitized
   
- [ ] Give a meaningful title to your PR
- [ ] Describe your changes
   
- [ ] Link any related issue in the description
   
- [ ] Link any dependent pull request in the description

If this PR adds a new feature or fixes a bug:

- [ ] I have added or updated relevant tests

If this PR modifies installation or updates packages:

- [ ] I have checked that installation works on all platforms (Windows, Linux, Mac ...)
    

- [ ] I have updated related documentations (installation commands, fix to specific problems ...)

If this PR is related to GUI:

- [ ] I have checked that GUIs affected by my changes are working properly.

If this PR affects the user:

- [ ] I have created a news fragment
   
- [ ] I have updated the user documentation

2023-08-08 14:58 UTC, Max-7 requested changes

2023-08-08 14:58 UTC, Max-7 commented on client/src/views/home/HomePage.vue
> +@/components/core/ms-select/MsSelectOption
??

2023-08-08 14:58 UTC, Max-7 commented on client/src/views/workspaces/WorkspacesPage.vue
> +@/components/core/ms-select/MsSelectOption
??

2023-08-08 14:58 UTC, Max-7 commented on client/src/components/core/ms-select/MsSelect.vue
> +@/components/core/ms-select/MsSelectOption
??

2023-08-08 14:58 UTC, Max-7 commented on client/src/components/workspaces/WorkspaceUserRole.vue
> +@/components/core/ms-select/MsSelectOption
??

2023-08-08 15:11 UTC, Max-7 approved these changes

2023-08-09 07:43 UTC, fabienSvtr approved these changes
Most of css class and TypeScript variables of components have been changed, don't think that was necessary but it works so that's fine.

2023-08-09 10:05 UTC, merged