Expose HumandHandle as a structure
Scille/parsec-cloud pull request #5053
Opened 2023-08-22 13:45 UTC by FirelightFlagboy

2023-08-23 10:30 UTC, touilleMan requested changes

2023-08-24 08:03 UTC, FirelightFlagboy commented on bindings/generator/generate.py
> +            return value + "()"
I'm not sure what you mean by that, that method is called in the jinja template.

did you mean that the code present in the method should be put in the template ?

2023-08-24 08:14 UTC, FirelightFlagboy commented on bindings/generator/generate.py
> +    getters: dict[str, str]
done

2023-08-24 08:14 UTC, FirelightFlagboy commented on bindings/generator/templates/binding_electron_meths.rs.j2
> +{% if struct.init is none %}
done

2023-08-24 09:03 UTC, FirelightFlagboy commented on bindings/generator/api/common.py
> +    custom_init: dict[str, str] = {
done

2023-08-24 12:02 UTC, FirelightFlagboy commented on bindings/generator/api/common.py
> +    custom_getters: dict[str, str] = {"email": "email", "label": "label"}
Currently we couldn't specify lifetime parameters in closure:

I've tried to use a closure instead as proposed but it result in the following error:

```
error: lifetime may not live long enough
   --> bindings/web/src/meths.rs:158:63
    |
158 | ... = ((|obj: &libparsec::HumanHandle| -> &str { obj.email() })(&rs_obj)).in...
    |               -                           -      ^^^^^^^^^^^ returning this value requires that `'1` must outlive `'2`
    |               |                           |
    |               |                           let's call the lifetime of this reference `'2`
    |               let's call the lifetime of this reference `'1`
```

2023-08-25 12:42 UTC, touilleMan commented on bindings/generator/generate.py
> +            return value + "()"
the template should call the function:
```
{ my_func }()
```

2023-08-25 13:05 UTC, FirelightFlagboy commented on bindings/generator/generate.py
> +            return value + "()"
ok

2023-08-25 13:33 UTC, FirelightFlagboy commented on bindings/generator/generate.py
> +            return value + "()"
The method `get_value` was removed

2023-08-30 10:38 UTC, touilleMan commented
I've created a branch implementing the closure-based approach we discussed on slack last week:

https://github.com/Scille/parsec-cloud/tree/expose-HumanHandle-as-struct-electric-boogaloo

(the important commit: https://github.com/Scille/parsec-cloud/commit/8f56cf9cb07547c7023509e136289acc64161275)

The in-elegant function-in-a-closure we were wondering seems pretty small and no big deal in the end:
```rust
|obj| { fn access(obj: &libparsec::HumanHandle) -> &str { obj.email() } access(obj) }
```

What do you think ?

2023-09-01 12:57 UTC, touilleMan commented
> It's not as statisfactory as I would like: clippy raise the following warning

You should be able to avoid this warning by doing:
```rust
{
  let custom_getter = |obj| {
    fn access(obj: &libparsec::HumanHandle) -> &str {
      obj.email()
    }
    access(obj)
  };
  custom_getter(&rs_obj)
}
```

(this is what is currently done for `custom_to_rs_string`&co)

2023-09-13 08:37 UTC, closed without merging