Merge `I32BasedType` & `U32BasedType` together into `NumberBasedType`
Scille/parsec-cloud pull request #5290
Opened 2023-09-22 07:34 UTC by FirelightFlagboy

2023-09-22 08:02 UTC, TimeEngineer requested changes
We don't want that, see: https://github.com/Scille/parsec-cloud/issues/3941

2023-09-22 08:36 UTC, FirelightFlagboy commented
I don't understand what's blocking can you elaborate ?

2023-09-22 08:42 UTC, TimeEngineer commented
> I don't understand what's blocking can you elaborate ?

The changes are in contradiction with the issue

2023-09-22 13:11 UTC, TimeEngineer commented on bindings/generator/templates/binding_electron_meths.rs.j2
>  JsNumber::new({{ mut_cx_ref }}, {{ rs_value }} as f64)
This number can be invalid for `u64` or `i64`

2023-10-12 14:35 UTC, FirelightFlagboy commented
Outdated, closing

2023-10-12 14:35 UTC, closed without merging