Add tests for `CertificatesOps` `add_certificates_batch` `device`
Scille/parsec-cloud pull request #5469
Opened 2023-10-10 15:56 UTC by TimeEngineer

closes #5468

2023-10-10 22:22 UTC, touilleMan requested changes

2023-10-10 22:22 UTC, touilleMan commented on libparsec/crates/client/src/certificates_ops/add.rs
> +#[derive(Debug, PartialEq, Eq)]
use `p_assert_matches` instead

2023-10-10 22:22 UTC, touilleMan commented on libparsec/crates/testbed/src/env.rs
> +
same changes than in #5467  ?

2023-10-11 10:19 UTC, TimeEngineer commented on libparsec/crates/client/src/certificates_ops/add.rs
> +#[derive(Debug, PartialEq, Eq)]
Done

2023-10-11 10:19 UTC, TimeEngineer commented on libparsec/crates/testbed/src/env.rs
> +
Done

2023-10-12 13:48 UTC, touilleMan approved these changes

2023-10-13 14:32 UTC, merged