5630 add documentation for recovery device feature
Scille/parsec-cloud pull request #5655
Opened 2023-10-27 14:17 UTC by FirelightFlagboy

2023-11-03 10:15 UTC, mmmarcos requested changes
Thanks for this docs! Some suggestions below.

Also, can you add a `newsfragment` for this so it will appear in the changelog?

If possible, it will be nice to also remove blur from images. It is more user friendly and consistent with other sections of the docs, like [Create new devices](https://docs.parsec.cloud/en/latest/userguide/new_device.html), using test data instead of blurring images.

2023-11-03 10:15 UTC, mmmarcos commented on docs/userguide/recovery_device.rst
> +      Nevertheless, you should not save it alongside the recovery device.
```suggestion
      The passphrase should be handled carefully like any other password.

      You can print out the passphrase and put-it in a safe to secure it.
      Nevertheless, you should not save it alongside the recovery file.
```

2023-11-03 10:15 UTC, mmmarcos commented on docs/userguide/recovery_device.rst
> +1. At that point, you select ``Recover a Device``, that will open a new modal:
```suggestion
1. In the Device recovery dialog, select ``Recover a Device``
```

2023-11-03 10:15 UTC, mmmarcos commented on docs/userguide/recovery_device.rst
> +   c. Enter the desired device name.
```suggestion
2. From here:

   a. Select the recovery file of the device you want to recover.
   b. Enter the passphrase for the recovery device.
   c. Enter a new name for the device.

   .. image:: screens/recovery_device_recover.png
      :alt: Recover a device modal
```

2023-11-03 10:15 UTC, mmmarcos commented on docs/userguide/recovery_device.rst
> +4. The last modal is a confirmation prompt indicating everything went fine, you can click on continue.
```suggestion
4. A message is displayed to confirm the device has been recovered, you can click `Continue`.
```

2023-11-03 10:15 UTC, mmmarcos commented on docs/userguide/recovery_device.rst
> +5. You will find the recovered device in the devices' list
```suggestion
5. You can now access Parsec as usual using the new recovered device from the devices' list
```

2023-11-09 10:28 UTC, FirelightFlagboy commented on docs/userguide/index.rst
> +    recovery_device
done

2023-11-09 16:47 UTC, mmmarcos approved these changes
:+1:

2023-11-09 16:47 UTC, mmmarcos commented on newsfragments/5630.doc.rst
> +That is an old feature that wasn't documented until now.
What about:
```suggestion
This feature was introduced in v2.6.0 and it was not documented until now.
```

2023-11-10 10:21 UTC, mmmarcos requested changes

2023-11-10 10:21 UTC, mmmarcos commented on docs/locale/fr/LC_MESSAGES/userguide/recovery_device.po
> +"nouveau mots de passe."
```suggestion
"nouveau mot de passe."
```

2023-11-10 10:21 UTC, mmmarcos commented on docs/locale/fr/LC_MESSAGES/userguide/recovery_device.po
> +"Cliquer sur ``Suivant``, vous serez demandé d'entrer le mots de passe pour "
```suggestion
"Cliquer sur ``Suivant``, vous serez demandé d'entrer le mot de passe pour "
```

2023-11-10 10:21 UTC, mmmarcos commented on docs/locale/fr/LC_MESSAGES/userguide/recovery_device.po
> +"La phrase de passe doit être manipulée comme n'importe quels mots de passe."
```suggestion
"La phrase de passe doit être manipulée comme n'importe quels mot de passe."
```

2023-11-10 10:21 UTC, mmmarcos commented on docs/locale/fr/LC_MESSAGES/userguide/recovery_device.po
> +"pour la sécuriser. Néanmoins, vous ne devez pas la sauvegarder à coter du "
```suggestion
"pour la sécuriser. Néanmoins, vous ne devez pas la sauvegarder à coté du "
```

2023-11-10 10:21 UTC, mmmarcos commented on docs/locale/fr/LC_MESSAGES/userguide/recovery_device.po
> +"Cliquer sur ``Suivant``, vous serez demandé d'entrer un nouveau mots de "
```suggestion
"Cliquer sur ``Suivant``, vous serez demandé d'entrer un nouveau mot de "
```

2023-11-10 10:21 UTC, mmmarcos commented on docs/locale/fr/LC_MESSAGES/userguide/recovery_device.po
> +"Dialogue de configuration du nouveau mots de passe pour l'appareil récupéré"
```suggestion
"Dialogue de configuration du nouveau mot de passe pour l'appareil récupéré"
```

2023-11-10 10:38 UTC, mmmarcos commented
There is some legacy entries that should be removed from the `.po` file:
* `#: ../../userguide/recovery_device.rst`: these entries do not include the line number and do not appear in the rst file
* `#: ../../userguide/recovery_device.rst:20`: these entries should be kept

2023-11-10 10:46 UTC, FirelightFlagboy commented
> `#: ../../userguide/recovery_device.rst`: these entries do not include the line number and do not appear in the rst file

Those texts comes from the `alt` of images. they would come back when you run `make intl-fr`

> `#: ../../userguide/recovery_device.rst:20`: these entries should be kept

I don't understand, we only have 1 entry for `../../userguide/recovery_device.rst:20`

2023-11-10 14:55 UTC, mmmarcos commented
> > #: ../../userguide/recovery_device.rst: these entries do not include the line number and do not appear in the rst file
> 
> Those texts comes from the alt of images. they would come back when you run make intl-fr

My bad, I thought it was a legacy text to remove. 
So if we keep those entries, why did you mark it fuzzy? shouldn't we fix translations?

> > #: ../../userguide/recovery_device.rst:20: these entries should be kept
> 
> I don't understand, we only have 1 entry for ../../userguide/recovery_device.rst:20

It was just an example of an entry containing a line number (`20`).

2023-11-10 14:58 UTC, FirelightFlagboy commented
> So if we keep those entries, why did you mark it fuzzy?

It was added by `sphinx-intl` :shrug: 

> shouldn't we fix translations?

How do I fix that ?

2023-11-13 07:54 UTC, merged