[MS] file list not selectable
Scille/parsec-cloud pull request #5679
Opened 2023-10-31 07:55 UTC by fabienSvtr

Fixed bug: item behind gradient background (footer) not selectable

closes #5678

2023-11-02 08:12 UTC, Max-7 requested changes
Few things:
- this only applies to files and users, not workspaces.
- in grid mode the counter becomes hidden behind the counter
- the item is still partially hidden behind the counter, is that the expected behavior?

A few screenshots to show some edge cases
![workspace-behind](https://github.com/Scille/parsec-cloud/assets/18075498/afa700c9-dc07-4eb8-9a96-35f60f15a9b0)

![item-behind](https://github.com/Scille/parsec-cloud/assets/18075498/cdf963ba-9ab4-49b4-b873-cd74fd5acdfa)

![behind](https://github.com/Scille/parsec-cloud/assets/18075498/b009556f-fb6c-4fed-8f99-c151772c1987)

2023-11-02 13:46 UTC, fabienSvtr commented
> Few things:
> 
> * this only applies to files and users, not workspaces.
> * in grid mode the counter becomes hidden behind the counter
> * the item is still partially hidden behind the counter, is that the expected behavior?
> 
> A few screenshots to show some edge cases ![workspace-behind](https://user-images.githubusercontent.com/18075498/279909143-afa700c9-dc07-4eb8-9a96-35f60f15a9b0.png)
> 
> ![item-behind](https://user-images.githubusercontent.com/18075498/279909166-cdf963ba-9ab4-49b4-b873-cd74fd5acdfa.png)
> 
> ![behind](https://user-images.githubusercontent.com/18075498/279909213-b009556f-fb6c-4fed-8f99-c151772c1987.png)

Workspace footer was missing a `div`, the footer UI is now the same for workspaces, files and users.

2023-11-10 10:16 UTC, Max-7 requested changes

2023-11-10 10:16 UTC, Max-7 commented on client/src/views/workspaces/WorkspacesPage.vue
> +        <div class="folder-footer__container">
Maybe not your fault, but it seems that the counter on the workspace page is black, whereas the counter on other pages (users or files) is gray.

2023-11-10 10:37 UTC, Max-7 approved these changes

2023-11-10 13:32 UTC, merged