[MS] Update About View
Scille/parsec-cloud pull request #5690
Opened 2023-10-31 17:41 UTC by fabienSvtr

- Update links in About View
- Update UI according to mockups (About Page & Version in Homepage)

#5592

2023-11-02 08:16 UTC, Max-7 approved these changes

2023-11-02 15:01 UTC, NicoTuxx requested changes
Multiple design problems on About page:
- [ ] The 'update' button colors for hover and focus/clicked states create weird effects (look in the linked video)
- [ ] The links have button appearance (Parsec Cloud, License...) why not, but the 'show changelog' who's behavior is a button one, has a link appearance, this is confusing for a user.
- [ ] The home page modal version has 2 titles, the 'about' and 'Parsec Cloud' just one after each other looks weird. (cf linked image)


https://github.com/Scille/parsec-cloud/assets/19772607/ea445a8d-a8b0-4d20-afe0-8656f4447a1d

![image](https://github.com/Scille/parsec-cloud/assets/19772607/9f176754-8925-4951-bf9a-4ff8e279c4bf)

2023-11-02 15:38 UTC, NicoTuxx commented on client/src/locales/en-US.json
> +        "licenseLink": "https://github.com/Scille/parsec-cloud/blob/master/LICENSE"
It's okay for the moment, I opened a new issue to take care of this specific point.

2023-11-13 15:22 UTC, NicoTuxx approved these changes

2023-11-15 15:15 UTC, FirelightFlagboy commented on client/src/locales/en-US.json
> +        "licenseLink": "https://github.com/Scille/parsec-cloud/blob/master/LICENSE",
Use raw link ?

```suggestion
        "licenseLink": "https://raw.githubusercontent.com/Scille/parsec-cloud/master/LICENSE",
```

2023-11-15 15:15 UTC, FirelightFlagboy commented on client/src/locales/fr-FR.json
> +        "licenseLink": "https://github.com/Scille/parsec-cloud/blob/master/LICENSE",
Use raw link ?

```suggestion
        "licenseLink": "https://raw.githubusercontent.com/Scille/parsec-cloud/master/LICENSE",
```

2023-11-15 15:42 UTC, merged