[MS] Handle errors in claim device
Scille/parsec-cloud pull request #5692
Opened 2023-11-02 07:57 UTC by Max-7

Closes #5624 

- [X] Keep changes in the pull request as small as possible
- [X] Ensure the commit history is sanitized
- [X] Give a meaningful title to your PR
- [X] Describe your changes
- [X] Link any related issue in the description

2023-11-02 13:02 UTC, fabienSvtr commented on client/src/views/home/DeviceJoinOrganizationModal.vue
> +  }
The same code is repeated 2 times in a row, should we use a logic operator `OR` with the two `const` above?

`const retrieveResult = await claimer.value.retrieveInfo(props.invitationLink);`
`const waitResult = await claimer.value.initialWaitHost();`


`if (!retrieveResult.ok || !waitResult.ok) {
...
}`

2023-11-02 13:38 UTC, NicoTuxx requested changes

2023-11-02 13:38 UTC, NicoTuxx commented on client/src/locales/fr-FR.json
> +            "unexpected": "Une erreur imprévue est survenue (raison: {reason}).",
```suggestion
            "unexpected": "Une erreur imprévue est survenue (raison : {reason}).",
```

2023-11-06 09:53 UTC, NicoTuxx approved these changes

2023-11-06 10:06 UTC, merged