feat: improve SettingsView; mutualize toggles style
Scille/parsec-cloud pull request #5740
Opened 2023-11-06 15:12 UTC by NicoTuxx

![image](https://github.com/Scille/parsec-cloud/assets/19772607/aef4fab1-3ad7-4ec0-b31c-4e78107338d0)

2023-11-06 16:03 UTC, fabienSvtr requested changes

2023-11-06 16:06 UTC, fabienSvtr requested changes

2023-11-06 16:06 UTC, fabienSvtr commented on client/src/locales/fr-FR.json
> +            "description": "Langue de l'application",
`"description": "Choisissez la langue que vous souhaitez utiliser"`

2023-11-06 16:06 UTC, fabienSvtr commented on client/src/locales/fr-FR.json
> +            "description": "Thème de l'application",
`Changez l'apparence de Parsec Cloud`

2023-11-07 06:14 UTC, Max-7 approved these changes

2023-11-07 10:15 UTC, fabienSvtr approved these changes

2023-11-07 12:07 UTC, merged