[MS] Fixed file list item background and options button
Scille/parsec-cloud pull request #5834
Opened 2023-11-20 10:37 UTC by Max-7

Two very small changes related to the file list item:
- correctly displays a background when selected
- hide the options button when at least one file is selected

- [X] Keep changes in the pull request as small as possible
- [X] Ensure the commit history is sanitized
- [X] Give a meaningful title to your PR
- [X] Describe your changes

2023-11-21 15:05 UTC, fabienSvtr commented
In `FileListItem.vue` we should remove the line 161 `:focus` because it creates a bug when we maintain left click and drag on a not selected item.

2023-11-21 15:25 UTC, fabienSvtr approved these changes

2023-11-24 11:58 UTC, NicoTuxx requested changes

2023-11-24 11:58 UTC, NicoTuxx commented on client/src/components/files/FileCard.vue
> +      @click.stop="
all the following code makes reading the template laborious, should be moved to a `onSomethingClick` function.

2023-11-24 11:58 UTC, NicoTuxx commented on client/src/components/files/FileListItem.vue
> +          menuOpened = true;
same as previous comment.

2023-11-24 11:58 UTC, NicoTuxx commented on client/src/components/users/UserCard.vue
> +        menuOpened = true;
same here too.

2023-11-24 11:58 UTC, NicoTuxx commented on client/src/components/users/UserListItem.vue
> +          menuOpened = true;
same.

2023-11-24 12:02 UTC, NicoTuxx requested changes
A weird behavior is happening when selecting elements and then clicking on an other one.
It only seems to happen when we click on the element himself, not his options button.
It does not happen when we click outside of the list too.
https://github.com/Scille/parsec-cloud/assets/19772607/46f8aa08-e1d6-48c0-b1d0-cb0e3c80d827

2023-11-24 12:06 UTC, Max-7 commented
> A weird behavior is happening when selecting elements and then clicking on an other one. It only seems to happen when we click on the element himself, not his options button. It does not happen when we click outside of the list too. https://github.com/Scille/parsec-cloud/assets/19772607/46f8aa08-e1d6-48c0-b1d0-cb0e3c80d827

It's because of the mocks. You're travelling inside the folder `Dir1` but since the mocks always returns the same files/folders, it feels like the selection is just removed. If you look at the header, you'll see that you are now inside `/Dir1` instead of `/`.

2023-11-27 18:01 UTC, NicoTuxx approved these changes

2023-11-27 18:11 UTC, merged