[MS] Add description on dropdown user role
Scille/parsec-cloud pull request #5960
Opened 2023-12-08 07:48 UTC by fabienSvtr

## What's new?
### What have changed?
The user can understand what the role or profile can do throughout the application.

### Where: 
* Greet new user (profile choice)
* Share workspace (role choice)

### Describe your changes (screenshots)
<img width="388" alt="image" src="https://github.com/Scille/parsec-cloud/assets/81075511/d0018c0f-d1a4-4049-adf5-a8251f642f1b">
<img width="481" alt="image" src="https://github.com/Scille/parsec-cloud/assets/81075511/b41e274e-c4e6-4eb1-86d6-8c46628b4ef8">

## Checklist

Before you submit this pull request, please make sure to:

- [x] Keep changes in the pull request as small as possible
- [x] Ensure the commit history is sanitized
- [x] Give a meaningful title to your PR
- [x] Describe your changes
- [x] Link any related issue in the description
- [x] Link any dependent pull request in the description

closes #5887

2023-12-11 10:10 UTC, Max-7 requested changes

2023-12-11 10:10 UTC, Max-7 commented on client/src/locales/fr-FR.json
> +                "description": "Can manage the organization and its users."
Missing translation.

2023-12-11 12:42 UTC, NicoTuxx requested changes

2023-12-12 07:05 UTC, fabienSvtr commented on client/src/common/translations.ts
> +import { MsWorkspaceRole } from '@/components/core/ms-types';
Done it.

2023-12-12 07:18 UTC, Max-7 requested changes

2023-12-12 07:18 UTC, Max-7 commented on client/src/common/translations.ts
> +export function translateWorkspaceRole(t: ComposerTranslation, role: WorkspaceRole | null): MsOption {
This should not return a `MsOption`. Just define a dummy interface above, something like
```typescript
interface WorkspaceRoleTranslation {
  label: string;
  description?: string;
}
````
and use this as a return value. It doesn't need to be exported, it's never going to be used outside this function, and it's fine.

2023-12-12 07:18 UTC, Max-7 commented on client/src/components/core/ms-types.ts
> +export interface MsOption {
No export needed.

2023-12-13 15:45 UTC, NicoTuxx approved these changes

2023-12-13 15:49 UTC, Max-7 approved these changes

2023-12-13 16:00 UTC, merged