[MS] Fixed long modal titles
Scille/parsec-cloud pull request #5998
Opened 2023-12-15 06:08 UTC by Max-7

Closes #5989

1. Shortened question modal titles (the one I've found)
2. Added confirmation when trying to close the greet device modal on some states
3. Custom texts for Yes/No
4. Custom color for Yes

- [X] Keep changes in the pull request as small as possible
- [X] Ensure the commit history is sanitized
- [X] Give a meaningful title to your PR
- [X] Describe your changes
- [X] Link any related issue in the description

2023-12-15 08:47 UTC, fabienSvtr requested changes

2023-12-15 08:47 UTC, fabienSvtr commented on client/src/locales/fr-FR.json
> +            "logoutConfirmQuestion": "Êtes-vous sur(e) de vouloir vous déconnecter ?",
sûr(e)*

2023-12-15 13:25 UTC, Max-7 commented on client/src/components/core/ms-modal/utils.ts
> +  keepMainModalHiddenOnYes?: boolean;
Renamed this variable from `redisplayMainModalOnYes` because it's easier to have a default "false-ish" value (missing variable counts as false).

2023-12-18 09:46 UTC, fabienSvtr commented on client/src/components/core/ms-modal/MsModal.vue
> +  //     return 'warning';
We will not have a `Success` and `Warning` button

2023-12-18 09:50 UTC, fabienSvtr approved these changes

2023-12-18 14:49 UTC, NicoTuxx approved these changes

2023-12-18 16:49 UTC, merged