Add tests for CertifOps: rename_realm
Scille/parsec-cloud pull request #6279
Opened 2024-01-30 18:19 UTC by TimeEngineer

2024-02-01 15:00 UTC, FirelightFlagboy commented on libparsec/crates/client/tests/unit/certif/rename_realm.rs
> +async fn empty(env: &TestbedEnv) {
```suggestion
async fn unknown_realm(env: &TestbedEnv) {
```

2024-02-01 19:59 UTC, touilleMan requested changes

2024-02-01 19:59 UTC, touilleMan commented on libparsec/crates/client/tests/unit/certif/rename_realm.rs
> +    ops.add_certificates_batch(
use `builder.certificates_storage_fetch_certificates("alice@dev1");`

2024-02-01 19:59 UTC, touilleMan commented on libparsec/crates/client/tests/unit/certif/rename_realm.rs
> +    ops.add_certificates_batch(
use `builder.certificates_storage_fetch_certificates("alice@dev1");`

2024-02-01 19:59 UTC, touilleMan commented on libparsec/crates/client/tests/unit/certif/rename_realm.rs
> +    ops.add_certificates_batch(
use `builder.certificates_storage_fetch_certificates("alice@dev1");`

2024-02-01 19:59 UTC, touilleMan commented on libparsec/crates/client/tests/unit/certif/rename_realm.rs
> +    ops.add_certificates_batch(
use `builder.certificates_storage_fetch_certificates("alice@dev1");`

2024-02-01 19:59 UTC, touilleMan commented on libparsec/crates/client/tests/unit/certif/rename_realm.rs
> +                keys_bundle: Bytes::from_static(b""),
parametrize the test so that  invalid `keys_bundle` and invalid `keys_bundle_access` can be both tested separately

2024-02-01 19:59 UTC, touilleMan commented on libparsec/crates/client/tests/unit/certif/rename_realm.rs
> +                key_index: 1,
parametrize the test to also test an invalid `key_index`

2024-02-14 14:54 UTC, touilleMan approved these changes
:clap:

2024-02-14 15:29 UTC, merged