[MS] Adds workspace role bulk assignment
Scille/parsec-cloud pull request #7275
Opened 2024-05-06 15:31 UTC by Max-7

https://www.figma.com/file/XW3SNWHV8BhPsPJpsOCV2h/Parsec-App?type=design&node-id=30161-85608&mode=design&t=dt6374A9svgzPN4L-0

Needs a little makeover.

- [X] Keep changes in the pull request as small as possible
- [X] Ensure the commit history is sanitized
- [X] Give a meaningful title to your PR
- [X] Describe your changes

2024-05-22 09:52 UTC, mmmarcos commented
If this is related to #7083, can you link the issue?

2024-05-31 11:16 UTC, Ironicbay requested changes
- The option should not be available on revoked users
- Text does not display properly in the popover
- I would suggest adding the option in the UsersPage action bar when a user is selected
![Screenshot 2024-05-31 at 13 13 49](https://github.com/Scille/parsec-cloud/assets/41511029/ff26dbcc-9e4b-475c-806b-50c3d1ea0774)

2024-05-31 11:41 UTC, Max-7 commented
> * The option should not be available on revoked users
It should. Revoked users keep their role so you may want to assign the role of a user you've revoked to someone else.

> * Text does not display properly in the popover
What do you mean?

> * I would suggest adding the option in the UsersPage action bar when a user is selected
Yeah but we can't select revoked users so it may seem a bit weird to be able to do the action from one place but not the other.

2024-05-31 11:52 UTC, Ironicbay approved these changes

2024-05-31 12:02 UTC, merged