Rework DateTime to use integer instead of float \o/
Scille/parsec-cloud pull request #7372
Opened 2024-05-22 11:27 UTC by touilleMan

depends on #7107

TODO:
- [ ] protocol tests
- [ ] types tests
- [ ] bindings
- [ ] web storage

2024-06-03 09:13 UTC, FirelightFlagboy approved these changes

2024-06-04 13:38 UTC, FirelightFlagboy requested changes
Some mistake where made during the rebase, I see duplicate commit

2024-06-04 14:25 UTC, FirelightFlagboy approved these changes

2024-06-04 16:16 UTC, vxgmichel approved these changes

2024-06-05 07:58 UTC, FirelightFlagboy approved these changes

2024-06-05 08:12 UTC, vxgmichel approved these changes

2024-06-05 08:54 UTC, FirelightFlagboy commented
Retried with a nuked cache

2024-06-05 09:20 UTC, merged