[MS] Add hover class to file and user items when menu is opened
Scille/parsec-cloud pull request #7500
Opened 2024-06-04 05:39 UTC by Max-7

Closes #7467 

- [X] Keep changes in the pull request as small as possible
- [X] Ensure the commit history is sanitized
- [X] Give a meaningful title to your PR
- [X] Describe your changes
- [X] Link any related issue in the description

2024-06-04 12:25 UTC, fabienSvtr approved these changes

2024-06-05 09:16 UTC, Max-7 commented on client/src/components/workspaces/WorkspaceListItem.vue
> +defineExpose({
Not needed.

2024-06-05 09:16 UTC, Max-7 commented on client/src/components/workspaces/WorkspaceCard.vue
> +defineExpose({
Not needed.

2024-06-05 09:32 UTC, NicoTuxx requested changes

2024-06-05 09:56 UTC, NicoTuxx approved these changes

2024-06-05 11:04 UTC, merged