[MS] Add trial section on sidebar
Scille/parsec-cloud pull request #7759
Opened 2024-07-23 07:38 UTC by fabienSvtr

## Checklist

Before you submit this pull request, please make sure to:

- [ ] Keep changes in the pull request as small as possible
   
- [ ] Ensure the commit history is sanitized
   
- [ ] Give a meaningful title to your PR
- [ ] Describe your changes
   
- [ ] Link any related issue in the description
   
- [ ] Link any dependent pull request in the description

link to #7699
close #7736

2024-07-24 08:11 UTC, Max-7 requested changes

2024-07-24 08:11 UTC, Max-7 commented on client/src/components/organizations/OrganizationCard.vue
> +  orgaNameOnly?: boolean;
`org` or `organization`. `Orga` is too French. This remark is also valid for your class names.

2024-07-24 08:11 UTC, Max-7 commented on client/src/components/organizations/OrganizationCard.vue
> +const storedDeviceDataDict = ref<{ [deviceId: string]: StoredDeviceData }>({});
Not initialized. But you could instead pass the `lastLogin` as a prop from the OrganizationList, so you don't have to query the stored device data.

2024-07-24 08:11 UTC, Max-7 commented on client/src/locales/fr-FR.json
> +            "description": "Vous êtes sur actuellement sur la version d'essai gratuite.",
Not valid French.

2024-07-24 08:11 UTC, Max-7 commented on client/src/views/sidebar-menu/SidebarMenuPage.vue
> +                    <span v-if="isTrialOrg">{{ userInfo ? userInfo.organizationId.substring(0, 2) : '' }}</span>
Wrong condition.

2024-07-24 08:11 UTC, Max-7 commented on client/src/views/sidebar-menu/SidebarMenuPage.vue
> +    const url = new URL(currentDevice.value.serverUrl);
This code is repeated twice in this PR, move it to a function.

2024-07-24 10:20 UTC, NicoTuxx requested changes

2024-07-24 10:20 UTC, NicoTuxx commented on client/src/components/organizations/OrganizationCard.vue
> +          class="orga-avatar-logo"
```suggestion
          class="org-avatar-logo"
```

2024-07-24 10:20 UTC, NicoTuxx commented on client/src/components/organizations/OrganizationCard.vue
It would be simpler to have only 'organization-card" instead of using it and 'org-card', choose only one for the whole file to simplify the SCSS.

2024-07-24 10:20 UTC, NicoTuxx commented on client/src/locales/fr-FR.json
> +            "subscribe": "S'abonnez maintenant"
Dear lord 🙏 
```suggestion
            "subscribe": "S'abonner maintenant"
```

2024-07-24 10:20 UTC, NicoTuxx commented on client/src/locales/fr-FR.json
> +            "tag": "version d'essai",
```suggestion
            "tag": "Version d'essai",
```

2024-07-24 10:20 UTC, NicoTuxx commented on client/src/views/sidebar-menu/SidebarMenuPage.vue
> +                  <ion-avatar class="orga-avatar body-lg">
```suggestion
                  <ion-avatar class="org-avatar body-lg">
```

2024-07-24 10:20 UTC, NicoTuxx commented on client/src/views/sidebar-menu/SidebarMenuPage.vue
> +                      class="orga-avatar-logo"
```suggestion
                      class="org-avatar-logo"
```

2024-07-24 10:52 UTC, fabienSvtr commented on client/src/components/organizations/OrganizationCard.vue
I've updated it throughout the project

2024-07-24 11:01 UTC, NicoTuxx approved these changes

2024-07-24 11:20 UTC, Max-7 requested changes

2024-07-24 11:20 UTC, Max-7 commented on client/src/common/organization.ts
> +  if (device && expirationDuration) {
No need to check the device, it's typed as `AvailableDevice`, meaning it will always have a value.

2024-07-24 11:20 UTC, Max-7 commented on client/src/components/organizations/OrganizationCard.vue
> +  lastLoginDevice?: StoredDeviceData;
Why not just use a `DateTime` for this?

2024-07-24 11:20 UTC, Max-7 commented on client/src/common/organization.ts
> +export function checkTrialAndSetExpiration(
You don't need another function to get the expirationDuration, the function for that already exists: `getDurationBeforeExpiration`. You just need a function to check if a device belongs to a trial organization.
`export function isTrialOrganizationDevice(device: AvailableDevice): boolean {
  // some code here
  return isTrialOrg;
}`

2024-07-24 11:20 UTC, Max-7 commented on client/src/components/organizations/OrganizationCard.vue
> +  if (expirationDuration.value) {
`expirationDuration` will always be undefined here. Instead:
```
isTrialOrg.value = isTrialOrganizationDevice(props.device);
if (isTrialOrg.value) {
  expirationDuration = getDurationBeforeExpiration(props.device.createdOn);
}
```

2024-07-24 11:20 UTC, Max-7 commented on client/src/views/devices/ImportRecoveryDevicePage.vue
> +          :last-login-device="storedDeviceDataDict[device.deviceId]"
In this case we don't care about the last login, don't set the prop.

2024-07-24 11:20 UTC, Max-7 commented on client/src/views/home/LoginPage.vue
> +          :last-login-device="storedDeviceDataDict[device.deviceId]"
You don't need the `last-login-device` here, you're hiding everything but the org name anyway.

2024-07-24 11:20 UTC, Max-7 commented on client/src/views/home/OrganizationListPage.vue
> +                :last-login-device="storedDeviceDataDict[device.deviceId]"
Use the optional chaining operator to pass the `lastLogin` directly:
`:last-login-device="storedDeviceDataDict[device.deviceId]?.lastLogin"`

2024-07-24 11:20 UTC, Max-7 commented on client/src/views/sidebar-menu/SidebarMenuPage.vue
> +  if (expirationDuration.value && currentDevice.value) {
Same as my other comment for set `isTrialOrg` and `expirationDuration`.

2024-07-24 14:14 UTC, fabienSvtr commented on client/src/components/organizations/OrganizationCard.vue
> +  lastLoginDevice?: StoredDeviceData;
Yes probably much easier

2024-07-25 06:16 UTC, Max-7 approved these changes

2024-07-25 19:10 UTC, merged