[MS] Delete & set default payment method
Scille/parsec-cloud pull request #7958
Opened 2024-08-09 07:30 UTC by Max-7

- [X] Keep changes in the pull request as small as possible
- [X] Ensure the commit history is sanitized
- [X] Give a meaningful title to your PR
- [X] Describe your changes

2024-08-12 13:29 UTC, NicoTuxx requested changes
- [x] When adding a new card, `set as default payment method` does refresh the card background, but not the card details.
https://github.com/user-attachments/assets/d1cbe110-fdf7-4399-8f14-0c7304833c56
- [ ] When deleting a card, an undesired skeleton-text is appearing.
https://github.com/user-attachments/assets/6919e8a5-08be-4f06-a2b9-84ccd5986ede
- [ ] When using `Set as default` it is combining the 2 previous bugs.
https://github.com/user-attachments/assets/72141646-7714-4990-93aa-00fd40a3111d
- [ ] When having an error on `Add new card`, missing translation (fr & en) (with and without 'set default').
- [ ] When having an error on `Add new card`, should not close the modal, force to restart whole process.
https://github.com/user-attachments/assets/f98d5257-3c30-4f75-a29f-a9eda9e7bdeb
- [ ] Missing checks on `Set default` button and API: a card can expired, we should hide the button in this case and at quickly as possible to leave the function if card is expired.
- [ ] Missing check on `Delete payment method` API function, it should check if the card is not the active one (even if the UX does not offer such possibility).
- [ ] Is the `Restart subscription` supposed to be working? I don't remember it exisiting in the actual merchant site, and here I've an error each time I tried it.
![image](https://github.com/user-attachments/assets/2966a4f8-7cdc-4d39-a88b-b971cc4c21c0)

2024-08-12 13:29 UTC, NicoTuxx commented on client/src/locales/fr-FR.json
> +            "savedCard": "Cartes enregistrées",
missing translations `setDefault` and `delete`
![image](https://github.com/user-attachments/assets/b200d54f-686a-4055-bd92-7e3645bbff63)

2024-08-12 16:19 UTC, NicoTuxx commented on client/src/locales/en-US.json
> +                "questionMessage": "Are you sure you want to the subscription?",
done

2024-08-12 16:20 UTC, NicoTuxx commented on client/src/locales/fr-FR.json
> +                "confirm": "reprendre mon abonnement",
done

2024-08-12 16:20 UTC, NicoTuxx commented on client/src/locales/fr-FR.json
> +            "savedCard": "Cartes enregistrées",
done

2024-08-13 05:16 UTC, Max-7 commented
* [X]  When having an error on `Add new card`, should not close the modal, force to restart whole process.
* [X]  Missing checks on `Set default` button and API: a card can expired, we should hide the button in this case and at quickly as possible to leave the function if card is expired.

* [ ]  Missing check on `Delete payment method` API function, it should check if the card is not the active one (even if the UX does not offer such possibility).

Does it matter? There's no button for it in the interface, and the BMS is the arbiter in this case, it will decide if it accepts it or not (and return an error).

* [X]  Is the `Restart subscription` supposed to be working? I don't remember it exisiting in the actual merchant site, and here I've an error each time I tried it.

It does, but it's per organization and I forgot to hide it we were in the `All organization` case, meaning it was trying to hit the route `**/organizations//subscribe` because it was missing the org id.  That's probably the case you encountered.

2024-08-13 13:33 UTC, NicoTuxx approved these changes

2024-08-14 05:36 UTC, merged