Add error type for parsing `InvitationType`
Scille/parsec-cloud pull request #8021
Opened 2024-08-13 15:06 UTC by FirelightFlagboy

Closes #8001

2024-08-14 08:18 UTC, touilleMan requested changes

2024-08-14 08:18 UTC, touilleMan commented on libparsec/crates/types/src/invite.rs
> +pub struct InvitationTypeParseError(String);
```suggestion
pub struct InvitationTypeParseError;
```

No need to display the invalid data

2024-08-14 12:57 UTC, FirelightFlagboy commented on libparsec/crates/types/src/invite.rs
> +pub struct InvitationTypeParseError(String);
done

2024-08-19 01:23 UTC, touilleMan approved these changes

2024-08-19 06:43 UTC, merged