[MS] Updated contract page
Scille/parsec-cloud pull request #8061
Opened 2024-08-19 13:30 UTC by fabienSvtr

## Describe your changes

<img width="1437" alt="image" src="https://github.com/user-attachments/assets/434f5ed0-0059-4cd0-afb6-93147edd5827">

## Checklist

Before you submit this pull request, please make sure to:

- [ ] Keep changes in the pull request as small as possible
   
- [ ] Ensure the commit history is sanitized
   
- [ ] Give a meaningful title to your PR
- [ ] Describe your changes
   
- [ ] Link any related issue in the description
   
- [ ] Link any dependent pull request in the description

closes #7967

2024-08-19 15:50 UTC, Max-7 requested changes
Blocking to make sure `bms/api.ts` gets the right default values back.

2024-08-20 14:44 UTC, NicoTuxx requested changes

2024-08-20 14:44 UTC, NicoTuxx commented on client/src/locales/en-US.json
> +            "loading": "Your contrat arrives",
```suggestion
            "loading": "Your contract arrives",
```

2024-08-20 14:44 UTC, NicoTuxx commented on client/src/locales/en-US.json
> +                "title": "Licence member | Licences members",
```suggestion
                "title": "License member | Licenses members",
```

2024-08-20 14:44 UTC, NicoTuxx commented on client/src/locales/en-US.json
> +                "title": "Licence storage",
```suggestion
                "title": "License storage",
```

2024-08-20 14:53 UTC, NicoTuxx approved these changes

2024-08-20 14:56 UTC, Max-7 approved these changes

2024-08-21 06:51 UTC, merged