[MS] Add Saas demo server
Scille/parsec-cloud pull request #8218
Opened 2024-09-02 09:30 UTC by fabienSvtr

Added a demo server in `environnement.ts` to get the demo server name.
We can access to the organization from the client area even if the test is a monthly subscription organization.

## Checklist

Before you submit this pull request, please make sure to:

- [ ] Keep changes in the pull request as small as possible
   
- [ ] Ensure the commit history is sanitized
   
- [ ] Give a meaningful title to your PR
- [ ] Describe your changes
   
- [ ] Link any related issue in the description
   
- [ ] Link any dependent pull request in the description

closes #8158

2024-09-02 10:20 UTC, Max-7 requested changes

2024-09-02 10:20 UTC, Max-7 commented on client/electron/src/setup.ts
> +        this.MainWindow.webContents.openDevTools();
Missing something.

2024-09-03 07:47 UTC, Ironicbay approved these changes

2024-09-03 14:19 UTC, Ironicbay approved these changes

2024-09-03 14:42 UTC, merged