[MS] Made 'Go to home' button in client area accessible when an org is chosen
Scille/parsec-cloud pull request #8501
Opened 2024-09-24 09:59 UTC by Ironicbay

Closes https://github.com/Scille/parsec-cloud/issues/8437

2024-09-24 10:06 UTC, Max-7 approved these changes

2024-09-24 10:06 UTC, Max-7 commented on client/src/views/client-area/ClientAreaSidebar.vue
> +  await navigateTo(Routes.Home, { skipHandle: true, query: { bmsOrganizationId: props.organization.parsecId } });
Also add `replace: true` in both options.

2024-09-24 10:10 UTC, NicoTuxx requested changes
Not what was expected

2024-09-26 15:02 UTC, Max-7 approved these changes

2024-09-26 18:31 UTC, NicoTuxx approved these changes

2024-09-26 18:48 UTC, merged