Improve libparsec client connection tests
Scille/parsec-cloud pull request #8598
Opened 2024-10-03 11:02 UTC by touilleMan

2024-10-03 11:34 UTC, FirelightFlagboy requested changes
Extract the commit that add support for dict in the serialization crate, that would make the PR simpler to review

2024-10-03 11:54 UTC, touilleMan commented
> Extract the commit that add support for dict in the serialization crate, that would make the PR simpler to review

This commit is part of #8471 (on which this PR is based on), here you should only need to review the last 3 commits

2024-10-03 12:04 UTC, FirelightFlagboy commented
> This commit is part of https://github.com/Scille/parsec-cloud/pull/8471 (on which this PR is based on), here you should only need to review the last 3 commits

Stacked PR should be done by setting the appropriate base (`master` vs `eula`), that was not the case

2024-10-23 07:05 UTC, FirelightFlagboy approved these changes

2024-10-23 09:42 UTC, AureliaDolo approved these changes

2024-10-30 10:33 UTC, merged