[MS] Update invoice traductions
Scille/parsec-cloud pull request #9097
Opened 2024-12-03 10:50 UTC by fabienSvtr

## Describe your changes

## Checklist

Before you submit this pull request, please make sure to:

- [ ] Keep changes in the pull request as small as possible
   
- [ ] Ensure the commit history is sanitized
- [ ] Give a meaningful title to your PR
- [ ] Describe your changes
- [ ] Link any related issue in the description
  
closes #8731
closes #8732

2024-12-03 16:40 UTC, fabienSvtr commented on client/src/services/translation.ts
> +  console.log('status', InvoiceStatus);
it will be removed

2024-12-03 18:12 UTC, NicoTuxx requested changes
The PR is not fixing every problem described in the linked issues: the icon alignment bug is still present.

![image](https://github.com/user-attachments/assets/3cccc4b0-7dfc-4ded-80c0-95c90b24f28f)
![image](https://github.com/user-attachments/assets/84ffb20b-5546-4332-b57e-0c56105c2535)

2024-12-03 18:12 UTC, NicoTuxx commented on client/src/services/translation.ts
> +  console.log('status', InvoiceStatus);
when?

2024-12-03 18:12 UTC, NicoTuxx commented on client/src/services/translation.ts
> +      return 'clientArea.invoices.status.Uncollectible';
why a capitale letter here and not the other status?

2024-12-04 06:50 UTC, Max-7 commented on client/src/locales/fr-FR.json
> +                "void": "Inconnu"
`uncollectible` doesn't mean `not found`, it means that we can't enforce the payment. `void` doesn't mean `unknown`, it means that it's not legally binding.

You can find an explanation for every status on the Stripe website https://docs.stripe.com/invoicing/overview.

2024-12-04 06:51 UTC, Max-7 commented on client/src/locales/fr-FR.json
> +                "ready": "À payer",
English has `toPay`, French has `ready`.

2024-12-04 06:51 UTC, Max-7 commented on client/src/services/translation.ts
> +import { InvoiceStatus } from '@/services/bms/types';
Import it from `@/services/bms`

2024-12-09 06:31 UTC, Max-7 approved these changes

2024-12-09 11:01 UTC, fabienSvtr commented
> The PR is not fixing every problem described in the linked issues: the icon alignment bug is still present.
> 
> ![image](https://private-user-images.githubusercontent.com/19772607/392086984-3cccc4b0-7dfc-4ded-80c0-95c90b24f28f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDIzMTQsIm5iZiI6MTczMzc0MjAxNCwicGF0aCI6Ii8xOTc3MjYwNy8zOTIwODY5ODQtM2NjY2M0YjAtN2RmYy00ZGVkLTgwYzAtOTVjOTBiMjRmMjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDExMDAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5YWVhZWQ0ODhmZjM1YzkwMmVhYWRhN2VlMmRhYTAyMmU2NTZjZmZlYWU0MjcyZjk0MjdkY2VkNTFiNmExNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WTcHEckX-1ATtHouj-2lWiqxRI9g3myfHTu0mpol4g8) ![image](https://private-user-images.githubusercontent.com/19772607/392087059-84ffb20b-5546-4332-b57e-0c56105c2535.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDIzMTQsIm5iZiI6MTczMzc0MjAxNCwicGF0aCI6Ii8xOTc3MjYwNy8zOTIwODcwNTktODRmZmIyMGItNTU0Ni00MzMyLWI1N2UtMGM1NjEwNWMyNTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDExMDAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ZWFlYWMxYjQ4NGU0NThlOTk2YjY5OWFjOTkyZTU3N2QzYWVmODQ1ZWI1NmI1YmJlY2Y5YWFjNzNlNGEyMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IbTdjA-9if9hsG-lmHQ8YGFL3BiSM-0rRHYICHCgQSw)

As discussed, I replaced the download icon, now included in megashark-lib.

2024-12-17 09:20 UTC, NicoTuxx approved these changes

2024-12-17 13:23 UTC, merged